[CmdletBinding()]
param(
    [string]$Destination = "D:\AgenticAI\VietDub",
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$source = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$destinationPath = [IO.Path]::GetFullPath($Destination)
if ($destinationPath.TrimEnd('\') -eq $source.TrimEnd('\')) {
    throw "Destination must not be the VideoDubbing source directory."
}

if ((Test-Path $destinationPath) -and (Get-ChildItem $destinationPath -Force | Select-Object -First 1)) {
    if (-not $Force) {
        throw "Destination is not empty. Re-run with -Force only after checking the path: $destinationPath"
    }
    Remove-Item -LiteralPath $destinationPath -Recurse -Force
}

$staging = Join-Path ([IO.Path]::GetDirectoryName($destinationPath)) (".vietdub-export-" + [guid]::NewGuid())
New-Item -ItemType Directory -Force -Path $staging | Out-Null

function Copy-Relative([string]$relative) {
    $from = Join-Path $source $relative
    $to = Join-Path $staging $relative
    if (-not (Test-Path $from)) { throw "Missing export source: $relative" }
    New-Item -ItemType Directory -Force -Path (Split-Path $to -Parent) | Out-Null
    Copy-Item -LiteralPath $from -Destination $to -Recurse -Force
}

# Copy a directory tree while skipping heavy/derived subdirectories (build
# output, installed dependencies) so the export never duplicates multi-GB
# artifacts such as the Rust target/ directory.
function Copy-Tree([string]$relative, [string[]]$excludeDirs) {
    $from = Join-Path $source $relative
    $to = Join-Path $staging $relative
    if (-not (Test-Path $from)) { throw "Missing export source: $relative" }
    New-Item -ItemType Directory -Force -Path $to | Out-Null
    $roboArgs = @($from, $to, "/E", "/NFL", "/NDL", "/NJH", "/NJS", "/NP", "/R:1", "/W:1")
    foreach ($dir in $excludeDirs) { $roboArgs += "/XD"; $roboArgs += (Join-Path $from $dir) }
    & robocopy @roboArgs | Out-Null
    $code = $LASTEXITCODE
    if ($code -ge 8) { throw "robocopy failed for ${relative} (exit code $code)" }
    $global:LASTEXITCODE = 0
}

try {
    @(
        "package.json", "package-lock.json", ".gitignore",
        "apps/api/app", "apps/api/requirements.txt", "apps/api/run_server.py",
        "apps/api/.env.omnivoice.example",
        "apps/api/omnivoice_local_service.py", "apps/api/videodubbing-api.spec",
        ".github", "scripts/build-release.ps1",
        "scripts/build-release.sh", "scripts/export-vietdub.ps1",
        "scripts/scan-distribution.ps1", "scripts/test-distribution.ps1",
        "scripts/make-backend-manifest.ps1",
        "packaging", "THIRD_PARTY_NOTICES.md", "LICENSES"
    ) | ForEach-Object { Copy-Relative $_ }

    # Desktop app: skip the multi-GB Rust target/, node_modules, dist and any
    # prebuilt sidecar binaries — all are regenerated by the build pipeline.
    Copy-Tree "apps/desktop" @("node_modules", "dist", "src-tauri\target", "src-tauri\binaries")

    Copy-Item -LiteralPath (Join-Path $source "packaging/.env.example") -Destination (Join-Path $staging ".env.example")
    Copy-Item -LiteralPath (Join-Path $source "packaging/README.distribution.md") -Destination (Join-Path $staging "README.md")

    # Voice assets under apps/api/app/assets (the OmniVoice default reference and
    # VieNeu preset previews) are intentionally retained — they are the user's
    # own distributable voice setup. scan-distribution.ps1 allowlists them.
    Get-ChildItem $staging -Directory -Recurse -Force |
        Where-Object { $_.Name -in @("__pycache__", ".pytest_cache") } |
        Sort-Object FullName -Descending |
        Remove-Item -Recurse -Force
    Get-ChildItem (Join-Path $staging "apps/desktop/src-tauri/resources/bin") -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -ne ".gitkeep" } | Remove-Item -Force

    & (Join-Path $source "scripts/scan-distribution.ps1") -Path $staging
    & (Join-Path $source "scripts/test-distribution.ps1") -Path $staging

    New-Item -ItemType Directory -Force -Path ([IO.Path]::GetDirectoryName($destinationPath)) | Out-Null
    if (Test-Path $destinationPath) {
        Remove-Item -LiteralPath $destinationPath -Force
    }
    Move-Item -LiteralPath $staging -Destination $destinationPath
    Write-Host "Clean VietDub source exported to: $destinationPath"
}
catch {
    if (Test-Path $staging) { Remove-Item -LiteralPath $staging -Recurse -Force }
    throw
}
